version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.3
  mac-ip-allowlist: {}

executors:
  mac-26:
    macos:
      xcode: 26.1.1
    resource_class: m4pro.medium

filters: &filters
  tags:
    only: /.*/

release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  integration-test:
    parameters:
      image:
        type: string
    macos:
      xcode: << parameters.image >>
    resource_class: m4pro.medium
    steps:
      - checkout
      - run:
          name: Create passlist
          command: |
            echo "1.1.1.1/32" > /tmp/passlist
            echo "192.168.4.0/22" >> /tmp/passlist
      - mac-ip-allowlist/setup:
          passlist_file: /tmp/passlist
      - run:
          name: Verify pf table
          command: |
            table_contents=$(sudo pfctl -t passlist -T show 2>&1 | awk '!/ALTQ/' | tr -d ' ')
            expected="1.1.1.1
            192.168.4.0/22"
            expected=$(echo "$expected" | tr -d ' ')
            if [ "$table_contents" = "$expected" ]; then
              echo "Passlist table matches expected contents"
            else
              echo "Passlist table does not match expected contents"
              echo "Expected:"
              echo "$expected"
              echo "Got:"
              echo "$table_contents"
              exit 1
            fi
      - run:
          name: Test connectivity - distiller
          command: curl -v -i https://app.circleci.com
      - mac-ip-allowlist/run_command:
          command_name: "Test connectivity - distiller-restricted"
          command: curl -v -i https://1.1.1.1

  test-brew:
    executor: mac-26
    steps:
      - checkout
      - run:
          name: Create passlist
          command: |
            echo "0.0.0.0/0" >> /tmp/passlist
      - mac-ip-allowlist/setup:
          passlist_file: /tmp/passlist
      - mac-ip-allowlist/run_command:
          command_name: Test brew
          command: brew install mtr

  test-python-venv:
    executor: mac-26
    steps:
      - checkout
      - run:
          name: Create passlist
          command: |
            echo "0.0.0.0/0" >> /tmp/passlist
      - mac-ip-allowlist/setup:
          passlist_file: /tmp/passlist
      - run:
          name: Transfer ownership to distiller-restricted
          command: sudo chown -R distiller-restricted "$PWD"
      - mac-ip-allowlist/run_command:
          command_name: Test python venv
          command: python -m venv .venv

  test-function-exporting:
    executor: mac-26
    steps:
      - checkout
      - run:
          name: Define test function
          command: |
            test_function() {
              echo "test function executed"
            }
            declare -f test_function >> "$BASH_ENV"
      - run:
          name: Create passlist
          command: echo "0.0.0.0/0" >> /tmp/passlist
      - mac-ip-allowlist/setup:
          passlist_file: /tmp/passlist
      - mac-ip-allowlist/run_command:
          command_name: Test function exporting
          command: |
            if ! type test_function > /dev/null 2>&1
            then
              echo "Shell function was not exported to distiller-restricted"
              exit 1
            fi
            echo "Shell function successfully exported to distiller-restricted"

  test-env-exporting:
    executor: mac-26
    steps:
      - checkout
      - run:
          name: Create passlist
          command: |
            echo "0.0.0.0/0" >> /tmp/passlist
      - mac-ip-allowlist/setup:
          passlist_file: /tmp/passlist
      - mac-ip-allowlist/run_command:
          command_name: Install gh
          command: brew install gh
      - mac-ip-allowlist/run_command:
          command_name: Test gh release download
          command: |
            if [ -z "$CIRCLE_BRANCH" ]
            then
              echo "Environment variables failed to export"
              exit 1
            fi
            echo "Environment variables successfully exported"


workflows:
  test-deploy:
    jobs:
      - integration-test:
          filters: *filters
          matrix:
            parameters:
              image: [15.4.0, 16.4.0, 26.0.0, 26.1.1]
      - test-brew:
          filters: *filters
      - test-python-venv:
          filters: *filters
      - test-function-exporting:
          filters: *filters
      - test-env-exporting:
          filters: *filters
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          circleci_ip_ranges: true
          enable_pr_comment: false
          orb_name: circleci/mac-ip-allowlist
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
            - integration-test
            - test-brew
            - test-python-venv
            - test-function-exporting
            - test-env-exporting
          context: orb-publisher
          filters: *release-filters
